# Default settings
default_api_url: https://redcapexternal.research.sickkids.ca/api/ # This is the default option for command line scripts that accept an API URL argument.

# Input paths
api_key_path: /Users/steven ufkes/redcap_directory/input/api_keys.yml # Scripts will pull API URLs and tokens from this file. Do not upload this file online.
event_ids_path: /Users/steven ufkes/redcap_directory/input/event_ids.yml # Some scripts will look here for the event_id associated with a REDCap event.

# Output paths
default_backups_dir: /Users/steven ufkes/redcap_directory/output/backups # This is the default directory to which backups will be written by backupProjects.py
